### ISSUE TITLE
[BUG] Plugin requires "com.intellij.modules.java"

### ISSUE THREAD

**Issue by vladmany** [Nordgedanken/auto_hot_key_jetbrains_plugin#20] opened 2020-07-07 18:04 UTC
**Describe the bug**
The plugin is not installed. Error message: Plugin "AutoHotkey Language" requires "com.intellij.modules.java" plugin to be installed.

**To Reproduce**
1. Go to https://plugins.jetbrains.com/plugin/13945-autohotkey-language/versions
2. Click on "Download" 0.2.0
3. Open PhpStorm 2020.1.2
4. Open File -> Settings... -> Plugins -> Install Plugin from Disk
5. Select downloaded plugin file "auto_hotkey-0.2.0.zip"
6. Click "RESTART IDE"

**Expected behavior**
The plugin is not activated. The error "Plugin Error. Plugin "AutoHotkey Language" requires "com.intellij.modules.java" plugin to be installed." appeared in Event Log

**Screenshots**
https://imgur.com/a/3a0n1xA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2020.1.2 Build #PS-201.7846.90, built on June 3, 2020

**Additional context**
-

**Comment by MTRNord** [comment] 2020-07-07 20:17
Duplicate of #16

**Closed by MTRNord** 2020-07-07 20:17 UTC
Labels: bug
