### ISSUE TITLE
[TODO] Add run configuration support

### ISSUE THREAD

**Issue by takanuva15** [Nordgedanken/auto_hot_key_jetbrains_plugin#11] opened 2020-05-10 13:48 UTC
**Tutorial:** Be able to create run configurations to provide native support for running scripts directly from IntelliJ (so we don't have to do hacks with bash scripts)
**Difficulty:** Hard
**How Important:** Medium

**Comment by MTRNord** [comment] 2020-05-10 16:16
Difficulty is more likely to be hard as it isn't yet documented by Jetbrains :/ Will need some digging in other olugins. But I agree it is quite important

**Comment by MTRNord** [comment] 2020-05-10 16:37
Actually it seems I am wrong. It is documented at https://www.jetbrains.org/intellij/sdk/docs/basics/run_configurations.html

**Comment by MTRNord** [comment] 2020-05-10 16:37
Will take a look at it now.

**Comment by MTRNord** [comment] 2020-05-10 17:21
![grafik](https://user-images.githubusercontent.com/1374914/81505950-53de3080-92f3-11ea-8c6e-03a3fdc407d9.png)

Ok getting this far is apparently the easier part. But this doesn't yet do anything. As that is... Undocumented... Argh :D

**Comment by MTRNord** [comment] 2020-05-10 17:26
![grafik](https://user-images.githubusercontent.com/1374914/81506054-21810300-92f4-11ea-8d23-7372a5be5931.png)

**Comment by takanuva15** [comment] 2020-05-10 17:29
Lol nice! Really there's only 2 things needed for an AHK run config:

- Specify what script to run
- Specify any arguments to the script

**Comment by MTRNord** [comment] 2020-05-10 17:45
I am working on that. Including command auto completion like the rust jetbrains plugin has ^^

**Comment by MTRNord** [comment] 2020-05-10 18:29
![grafik](https://user-images.githubusercontent.com/1374914/81507338-f9e26880-92fc-11ea-8ccb-c2243788aacd.png)

Autocompletion works :)

**Comment by MTRNord** [comment] 2020-05-10 20:19
Will finish this hopefully tomorrow. Got carried away by trying to fix functions in the grammar implementation xD

**Comment by MTRNord** [comment] 2020-05-11 15:58
This is now in 0.1.3. It doesn't yet actually run the task. Thats still WIP. THe function stuff took longer than expected.

**Comment by takanuva15** [comment] 2020-05-11 23:45
Hmm...we shouldn't put half-working in the release; that will cause issues and we might get people raising issues even though it's not supposed to work yet. Let's improve the workflow for this plugin's development by adding a develop branch and individual branches for each issue that's being completed. That way there's no need to release something that's not fully working yet.

(basically we will create a new branch off of develop when we are working on an issue, and then when we have finished it, we can make a pull request (PR) from our branch to develop. If the PR is good, it gets merged and then we can make a PR from develop to master branch to officially release the code to jetbrains)

**Comment by MTRNord** [comment] 2020-05-12 07:36
The Problem is just the grammar isn't finished yet. I know it isn't optimal but I am trying to push make it work as fast as possible. In future when we got a more stable base to work with the Releases will Happen slower and with more stable Features

**Comment by MTRNord** [comment] 2020-06-07 11:51
Fixed by #15

**Closed by MTRNord** 2020-06-07 11:51 UTC
Labels: enhancement
